#lang sicp
(define (fac n)
  (define (fi p c)
    (if (< c (+ n 1)) (fi (* p c) (+ c 1)) p))
  (fi 1 1))

(define (coeff n r)
  (if (> r (- n r))
      (coeff n (- n r))
      (cond ((= r 0) 1)
            ((= r 1) n)
            (else (/ (fac n) (* (fac (- n r)) (fac r)))))))

(define (layer n)
  (define (iter r)
          (display (coeff (- n 1) r)) (display " ")
                   (if (= r (- n 1))
                        (newline)
                        (iter (+ r 1))))
  (iter 0))

(define (display-space n)
  (cond ((= n 0) (display ""))
        (else (display " ") (display-space (- n 1)))))

(define (display-pascal n)
  (define (iter i)
    (display-space (- n i))
    (layer i)
    (if (= i n)
        (newline)
        (iter (+ i 1))))
  (iter 1))

(display-pascal 10)
